---
- hosts: all
  remote_user: root
  become: yes
  tasks:
    - name: install postgresql repo
      yum:
        name: https://download.postgresql.org/pub/repos/yum/9.5/redhat/rhel-7-x86_64/pgdg-centos95-9.5-2.noarch.rpm
        state: present
    - name: install epel repo
      yum:
        name: http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present
    - name: upgrade all packages, excluding kernel & foo related packages
      yum:
        name: '*'
        state: latest
        exclude: kernel*
    - name: install required packages for dev
      yum: pkg={{item}} state=installed
      with_items:
       - git
       - m4
       - make
       - which
       - postgresql95-server
       - python-virtualenv
       - python-virtualenvwrapper
