---
- hosts: all
  remote_user: root
  become: yes
  tasks:
    - name: install extra repos
      yum:
        name: "{{ item }}"
        state: present
      with_items:
         - http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
         - http://software.internet2.edu/rpms/el7/x86_64/main/RPMS/Internet2-repo-0.7-1.noarch.rpm
         - https://download.postgresql.org/pub/repos/yum/9.5/redhat/rhel-7-x86_64/pgdg-centos95-9.5-2.noarch.rpm
    - name: upgrade all packages, excluding kernel related packages
      yum:
        name: '*'
        state: latest
        exclude: kernel*
    - name: install required packages for dev
      yum: pkg={{item}} state=installed
      with_items:
       - git
       - m4
       - make
       - ntp
       - which
       - python-devel
       - python-virtualenv
       - python-virtualenvwrapper
       - vim
    - name: build and install pscheduler (this could take a few minutes, watch build.log in host source dir for progress)
      command: make fresh
      args:
          chdir: /perfsonar/pscheduler
          creates: /perfsonar/pscheduler/build.log
    - name: restart pscheduler-runner
      service:
          name: pscheduler-runner
          state: restarted
